coverage:
  ignore:
    - "mockclient/*"
  notify:
    webhook:
      default:
        url: "https://master.gaiahub.io:444/wh/5a866f9b-98c9-438d-a8d4-53cf4ae9599c/4936fb9b9a2799b2ee03e10003b68aaa3f155324"
